services:
  - type: web
    name: blackhorse-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python discordbot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000
    plan: free 